site_name: Geonovum Werkwijze
repo_url: https://github.com/Geonovum/handleiding-GitHub
edit_uri: blob/main/docs/
nav:
    - GitHub:
        - 'GitHub Intro': GitHub-Inleiding.md
        - 'Manual': GitHub.md
    - Imvertor: Imvertor.md
    - Markdown: Markdown.md
    - ReSpec:
        - Manual: ReSpec.md
        - Checklists: ReSpec-Checklists.md
    - Subversion: Subversion.md
    - EA: PrimitieveDatatypes.md
    - GML: GML.md
